language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 7.1
    - 7.2
    - 7.3
    - nightly

env:
    matrix:
        - SYMFONY_VERSION=2
        - SYMFONY_VERSION=3
        - SYMFONY_VERSION=4

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

install:
    - test "$SYMFONY_VERSION" -eq 4 || composer require --no-update "symfony/lts:^$SYMFONY_VERSION"
    - composer update
    - gem install sass

script:
    - bin/phpunit -v
    - Tests/console assetic:dump
